services:
  db:
    image: postgres
    hostname: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env.dev
  web:
      # image: cr.yandex/crpmse562n8qa4i27dh9/shortener:v1
      build: .
      entrypoint: ./docker-entrypoint.sh
      #command: python manage.py runserver 0.0.0.0:8000
      env_file: .env.dev
      ports:
        - "8000:8000"

      depends_on:
        - db