# Generated by Django 3.2 on 2022-11-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_auto_20220703_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
