# Generated by Django 4.0.3 on 2023-01-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_teacher_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='successfull',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teachers_price',
            field=models.FloatField(default=0),
        ),
    ]
