# Generated by Django 4.0.3 on 2023-01-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_lesson_successfull_lesson_teachers_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='successfull',
        ),
        migrations.AddField(
            model_name='lesson',
            name='state',
            field=models.CharField(choices=[('A', 'Await'), ('F', 'Faild'), ('S', 'Success')], default='A', max_length=1),
        ),
    ]
